#ifndef WKWORMORDER_CONSTANTS_H
#define WKWORMORDER_CONSTANTS_H

namespace Constants {
	enum ClassType {
		ClassType_None = 0,
		ClassType_Task,
		ClassType_GameTask,
		ClassType_GameCollisionTask,
		ClassType_Task_Control,
		ClassType_Task_Game,
		ClassType_Task_TurnGame,
		ClassType_Task_Filter,
		ClassType_Task_Mine,
		ClassType_Task_Canister,
		ClassType_Task_Team,
		ClassType_Task_Missile,
		ClassType_Task_Arrow,
		ClassType_Task_Animation,
		ClassType_Task_Dirt,
		ClassType_Task_Crate,
		ClassType_Task_Flame,
		ClassType_Task_AirStrike,
		ClassType_Task_Worm,
		ClassType_Task_OldWorm,
		ClassType_Task_Drill,
		ClassType_Task_Cross,
		ClassType_Task_Smoke,
		ClassType_Task_Cloud,
		ClassType_Task_Fire,
		ClassType_Task_Gass,
		ClassType_Task_FireBall,
		ClassType_Task_SeaBubble,
		ClassType_Task_Land,
		ClassType_Task_ScoreBubble,
		ClassType_Task_OilDrum,
		ClassType_Task_CPU,
		ClassType_SpriteAnimation,
		ClassType_CollisionManager,
		ClassType_MAX
	};

	enum TaskMessage {
		TaskMessage_None = 0,
		TaskMessage_FrameStart,
		TaskMessage_FrameFinish,
		TaskMessage_RenderScene,
		TaskMessage_ProcessInput,
		TaskMessage_UpdateNonCritical,
		TaskMessage_MachineFinished,
		TaskMessage_CrateCollected,
		TaskMessage_StateChecksum,
		TaskMessage_MachineReady,

		TaskMessage_WormDrowned = 11,
		TaskMessage_FrameNumber,
		TaskMessage_MachineQuit,
		TaskMessage_EnableCheat,
		TaskMessage_PlayerChat,
		TaskMessage_CameraAuto,
		TaskMessage_CursorMoved,
		TaskMessage_GirderChanged,
		TaskMessage_StrikeChanged,
		TaskMessage_TeamVictory,
		TaskMessage_GameOver,
		TaskMessage_ExitMode,
		TaskMessage_Hurry,


		TaskMessage_ThinkingShow = 26,
		TaskMessage_ThinkingHide,
		TaskMessage_Explosion,
		TaskMessage_ExplosionReport,
		TaskMessage_MoveLeft,
		TaskMessage_MoveRight,
		TaskMessage_MoveUp,
		TaskMessage_MoveDown,
		TaskMessage_FaceLeft,
		TaskMessage_FaceRight,
		TaskMessage_Jump,
		TaskMessage_JumpUp,
		TaskMessage_FireWeapon,
		TaskMessage_ReleaseWeapon,
		TaskMessage_SkipGo,
		TaskMessage_Freeze, //added

		TaskMessage_Surrender = 43,
		TaskMessage_DetonateWeapon,
		TaskMessage_MoveWeaponLeft,
		TaskMessage_MoveWeaponRight,
		TaskMessage_SelectFuse,
		TaskMessage_SelectHerd,
		TaskMessage_SelectBounce,
		TaskMessage_SelectCursor,
		TaskMessage_SelectWeapon,
		TaskMessage_StartTurn,
		TaskMessage_PauseTurn,
		TaskMessage_ResumeTurn,
		TaskMessage_FinishTurn,
		TaskMessage_TurnStarted,
		TaskMessage_TurnFinished,
		TaskMessage_SuddenDeath,
		TaskMessage_DamageWorms,
		TaskMessage_RetreatStarted,
		TaskMessage_RetreatFinished,
		TaskMessage_ApplyPoison,
		TaskMessage_SetWorm,
		TaskMessage_KillWorm,


		TaskMessage_AdvanceWorm = 67,
		TaskMessage_ShowDamage,
		TaskMessage_EnableWeapons,
		TaskMessage_DisableWeapons,
		TaskMessage_WormMoved,
		TaskMessage_WormDamaged,
		TaskMessage_WeaponReleased,
		TaskMessage_WeaponFinished,
		TaskMessage_SpecialImpact,
		TaskMessage_WeaponCreated,
		TaskMessage_WeaponHoming,
		TaskMessage_WeaponDestroyed,
		TaskMessage_WeaponClaimControl,
		TaskMessage_WeaponReleaseControl,
		TaskMessage_PoisonWorm,


		TaskMessage_SetWind = 84,
		TaskMessage_GameText,
		TaskMessage_CreateAnimation,

		TaskMessage_BringForward = 88,
		TaskMessage_RaiseWater,
		TaskMessage_NukeBlast,
		TaskMessage_Armageddon,
		TaskMessage_DetonateCrate,
		TaskMessage_Earthquake,
		TaskMessage_ScalesOfJustice,

		TaskMessage_PauseTimer = 96,
		TaskMessage_ResumeTimer,
		TaskMessage_MoveSpecial,
		TaskMessage_StateWrongChecksum,
		TaskMessage_UpdateTween,
		TaskMessage_ProcessInputTween,
		TaskMessage_TimeReceivedObsolete,
		TaskMessage_Transferred,
		TaskMessage_TransferTimeFreq,
		TaskMessage_UpdatePanelTween,
		TaskMessage_StateWrongInitChecksum,
		TaskMessage_FrameFinishFiller,
		TaskMessage_MachineEvent,
		TaskMessage_InvalidDataCompressed,
		TaskMessage_InvalidDataUncompressed,
		TaskMessage_PacketIndexJump,
		TaskMessage_CancelPending,
		TaskMessage_BulletExplosion,
		TaskMessage_FrameNumberWinsock
	};

}

#endif //WKWORMORDER_CONSTANTS_H
